{% set name = "uproot-browser" %}
{% set version = "0.8.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uproot_browser-{{ version }}.tar.gz
  sha256: f80732d1297e46b0ef4f2c8e513df123494820e987c43532449bdfcb1b4d5d1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - uproot-browser = uproot_browser.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - awkward >=1
    - click >=8
    - click-default-group >=1.2
    - hist >=2.4
    - lz4
    - numpy >=1.13.3
    - plotext >=5.2.7
    - python >={{ python_min }}
    - rich >=13.3.3
    - textual >=0.18
    - typing_extensions
    - uproot >=5

test:
  source_files:
    - tests
  imports:
    - uproot_browser
  commands:
    - pip check
    - curl -LO https://github.com/scikit-hep/scikit-hep-testdata/raw/v0.4.12/src/skhep_testdata/data/uproot-Event.root
    - uproot-browser plot uproot-Event.root:hstat
    - pytest
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=6
    - pytest-asyncio
    - scikit-hep-testdata

about:
  home: https://pypi.org/project/uproot-browser/
  summary: Tools to inspect ROOT files with uproot
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
