context:
  name: uproot-browser
  version: "0.8.1"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/uproot_browser-${{ version }}.tar.gz
  sha256: 6846d659bdbfcb04f08cd7a99fda4e4a5f1182fa23d3c6af76f20e1cc53fcd98

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv
  python:
    entry_points:
      - uproot-browser = uproot_browser.__main__:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - awkward >=2
    - click >=8
    - click-default-group >=1.2
    - hist >=2.4
    - lz4 >=2
    - numpy >=1.18
    - plotext >=5.2.8
    - python >=${{ python_min }}
    - rich >=13.3.3
    - textual >=0.86
    - typing_extensions
    - uproot >=5

tests:
  - python:
      imports:
        - uproot_browser
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
        - pyproject.toml
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest >=8
        - pytest-asyncio
        - scikit-hep-testdata >=0.4.10
    script:
      - curl -LO https://github.com/scikit-hep/scikit-hep-testdata/raw/v0.4.12/src/skhep_testdata/data/uproot-Event.root
      - uproot-browser plot uproot-Event.root:hstat
      - pytest

about:
  summary: Tools to inspect ROOT files with uproot
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/uproot-browser/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
